include:
  package:lint/analysis_options.yaml
  package:effective_dart/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error