name: travel_list
description: Checklists for trips and travels

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.4.0
  another_flushbar: ^1.12.30
  auto_route: ^7.8.4
  bloc_concurrency: ^0.2.2
  cloud_firestore: ^4.12.1
  cool_stepper: ^1.2.1
  dartz: ^0.10.1
  fake_cloud_firestore: ^2.4.3
  firebase_auth: ^4.12.0
  firebase_auth_mocks: ^0.13.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_datetime_picker: ^1.5.1
  flutter_hooks: ^0.20.3
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: ^6.1.5
  google_sign_in_mocks: ^0.3.0
#  implicitly_animated_reorderable_list: ^0.4.2
  injectable: ^2.3.2
  intl: any
  json_annotation: ^4.8.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  uuid: ^4.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.4.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true