name: travel_list
description: Checklists for trips and travels

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  auto_route: ^3.2.4
  bloc_concurrency: ^0.2.0
  cloud_firestore: ^3.1.13
  cool_stepper: ^1.2.1
  dartz: ^0.10.1
  fake_cloud_firestore: ^1.2.2
  firebase_auth: ^3.3.15
  firebase_auth_mocks: ^0.8.4
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_hooks: ^0.18.3
  flutter_slidable: ^1.2.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_sign_in: ^5.3.0
  google_sign_in_mocks: ^0.2.1
  implicitly_animated_reorderable_list: ^0.4.2
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  mocktail: ^0.3.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  uuid: ^3.0.6

dev_dependencies:
  auto_route_generator: ^3.2.3
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.6
  lint: ^1.8.2

flutter:
  uses-material-design: true
