// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaHXcqGuHyUMuafg6QTP4Alq79toPrX28',
    appId: '1:16023612489:android:3c05c26ec6d9225837e398',
    messagingSenderId: '16023612489',
    projectId: 'travel-list-dee6b',
    databaseURL: 'https://travel-list-dee6b.firebaseio.com',
    storageBucket: 'travel-list-dee6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJsfXap0zUckp3yAvl1XdiqKRDcqbhQ4',
    appId: '1:16023612489:ios:e2c8c392b4d27fc237e398',
    messagingSenderId: '16023612489',
    projectId: 'travel-list-dee6b',
    databaseURL: 'https://travel-list-dee6b.firebaseio.com',
    storageBucket: 'travel-list-dee6b.appspot.com',
    androidClientId: '16023612489-5tjprkp152fcv82aca1msbg2n8hcf47t.apps.googleusercontent.com',
    iosClientId: '16023612489-6kcff5r5dl6q4gf86umnonfklhgv2els.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelList',
  );
}
